name: GitHub Pages CI/CD

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Github Actions
        run: echo Hello Github Actions!
      # - name: Echo env
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     echo "Github Token ${GITHUB_TOKEN}"
      #     echo "Github Ref ${GITHUB_REF}"
      #     echo "Github SHA ${GITHUB_SHA}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      # - name: Lint
      #   run: npm run lint
      - name: Test
        run: npm run test
      - name: PreBuild
        run: mkdir dist
      - name: Build
        run: SHA_SHORT=${GITHUB_SHA::7} npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
